"""
Report Generator
Generate PDF reports from simulation results.
"""

from datetime import datetime
from typing import Dict, Any, List, Optional
from pathlib import Path
import io


class ReportGenerator:
    """Generate PDF reports from GridSense analysis."""
    
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(
        self,
        title: str,
        summary: Dict[str, Any],
        forecast_data: Optional[Dict[str, Any]] = None,
        simulation_results: Optional[Dict[str, Any]] = None,
        recommendations: Optional[List[str]] = None
    ) -> bytes:
        """
        Generate a PDF report.
        
        Args:
            title: Report title
            summary: Summary statistics dictionary
            forecast_data: Forecast results
            simulation_results: Simulation results
            recommendations: List of recommendations
        
        Returns:
            PDF content as bytes
        """
        try:
            from fpdf import FPDF
        except ImportError:
            # Fallback to text report
            return self._generate_text_report(
                title, summary, forecast_data, simulation_results, recommendations
            )
        
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Title Page
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 24)
        pdf.cell(0, 20, '', ln=True)
        pdf.cell(0, 15, 'GridSense Report', ln=True, align='C')
        pdf.set_font('Helvetica', '', 16)
        pdf.cell(0, 10, title, ln=True, align='C')
        pdf.cell(0, 10, '', ln=True)
        pdf.set_font('Helvetica', '', 12)
        pdf.cell(0, 10, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', ln=True, align='C')
        
        # Summary Section
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 16)
        pdf.cell(0, 10, 'Executive Summary', ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.cell(0, 5, '', ln=True)
        
        pdf.set_font('Helvetica', '', 11)
        for key, value in summary.items():
            if isinstance(value, float):
                value = f"{value:,.2f}"
            elif isinstance(value, dict):
                value = str(value)
            pdf.cell(0, 8, f"{key}: {value}", ln=True)
        
        # Forecast Section
        if forecast_data:
            pdf.cell(0, 10, '', ln=True)
            pdf.set_font('Helvetica', 'B', 16)
            pdf.cell(0, 10, 'Load Forecast Analysis', ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.cell(0, 5, '', ln=True)
            
            pdf.set_font('Helvetica', '', 11)
            for key, value in forecast_data.items():
                if isinstance(value, float):
                    value = f"{value:,.2f}"
                pdf.cell(0, 8, f"{key}: {value}", ln=True)
        
        # Simulation Section
        if simulation_results:
            pdf.add_page()
            pdf.set_font('Helvetica', 'B', 16)
            pdf.cell(0, 10, 'Simulation Results', ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.cell(0, 5, '', ln=True)
            
            pdf.set_font('Helvetica', '', 11)
            for key, value in simulation_results.items():
                if key == 'risk_levels' or key == 'timestamps':
                    continue  # Skip large arrays
                if isinstance(value, float):
                    value = f"{value:,.2f}"
                elif isinstance(value, list):
                    if len(value) > 5:
                        value = f"{len(value)} items"
                    else:
                        value = ', '.join(str(v) for v in value)
                pdf.cell(0, 8, f"{key}: {value}", ln=True)
        
        # Recommendations Section
        if recommendations:
            pdf.cell(0, 10, '', ln=True)
            pdf.set_font('Helvetica', 'B', 16)
            pdf.cell(0, 10, 'Recommendations', ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.cell(0, 5, '', ln=True)
            
            pdf.set_font('Helvetica', '', 11)
            for i, rec in enumerate(recommendations, 1):
                pdf.multi_cell(0, 8, f"{i}. {rec}")
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font('Helvetica', 'I', 8)
        pdf.cell(0, 10, 'Generated by GridSense - Smart Grid Load Forecasting System', 0, 0, 'C')
        
        return pdf.output()
    
    def _generate_text_report(
        self,
        title: str,
        summary: Dict[str, Any],
        forecast_data: Optional[Dict[str, Any]] = None,
        simulation_results: Optional[Dict[str, Any]] = None,
        recommendations: Optional[List[str]] = None
    ) -> bytes:
        """Fallback text report when FPDF is not available."""
        lines = [
            "=" * 60,
            "GRIDSENSE REPORT",
            "=" * 60,
            "",
            f"Title: {title}",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "-" * 40,
            "EXECUTIVE SUMMARY",
            "-" * 40,
        ]
        
        for key, value in summary.items():
            if isinstance(value, float):
                value = f"{value:,.2f}"
            lines.append(f"  {key}: {value}")
        
        if forecast_data:
            lines.extend([
                "",
                "-" * 40,
                "LOAD FORECAST ANALYSIS",
                "-" * 40,
            ])
            for key, value in forecast_data.items():
                if isinstance(value, float):
                    value = f"{value:,.2f}"
                lines.append(f"  {key}: {value}")
        
        if simulation_results:
            lines.extend([
                "",
                "-" * 40,
                "SIMULATION RESULTS",
                "-" * 40,
            ])
            for key, value in simulation_results.items():
                if key in ['risk_levels', 'timestamps', 'loads']:
                    continue
                if isinstance(value, float):
                    value = f"{value:,.2f}"
                elif isinstance(value, list) and len(value) > 5:
                    value = f"{len(value)} items"
                lines.append(f"  {key}: {value}")
        
        if recommendations:
            lines.extend([
                "",
                "-" * 40,
                "RECOMMENDATIONS",
                "-" * 40,
            ])
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"  {i}. {rec}")
        
        lines.extend([
            "",
            "=" * 60,
            "Generated by GridSense",
            "=" * 60,
        ])
        
        return "\n".join(lines).encode('utf-8')
    
    def save_report(
        self,
        content: bytes,
        filename: Optional[str] = None
    ) -> str:
        """Save report to file."""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"gridsense_report_{timestamp}.pdf"
        
        filepath = self.output_dir / filename
        
        with open(filepath, 'wb') as f:
            f.write(content)
        
        return str(filepath)


